Blog/Models/Post/BasicPostModel.cs
using System.ComponentModel.DataAnnotations;


namespace Blog.App.Models.Post
{
    //use basic
    public class BasicPostModel
    {
        public long Id { get; set; }
        public string PostTitle { get; set; }

        [Required]
        public string PostText { get; set; }
        public string DatePublished { get; set; }
        public long BlogId { get; set; }

    }
}

Blog/Models/Post/BasicPostModelWithTagsAndUser.cs
using Blog.App.Models.Tag;
using Blog.App.Models.User;
using System.Collections.Generic;


namespace Blog.App.Models.Post
{
    //!!!!!!tags, use for derived
    public class BasicPostModelWithTagsAndUser : BasicPostModel
    {
        public BasicUserModel User { get; set; }
        public List<TagModel> Tags { get; set; }
    }
}

Blog/Models/Post/EditPostModel.cs
using Blog.App.Models.Tag;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace Blog.App.Models.Post
{
    public class EditPostModel
    {
        public long Id { get; set; }
        public long BlogId { get; set; }

        [Required]
        public string PostTitle { get; set; }

        [Required]
        public string PostText { get; set; }
        public List<TagModel> Tags { get; set; }
    }

}

Blog/Models/Post/EditablePostModel.cs
using Automapper.ModelsConverters.Attributes;

namespace Blog.App.Models.Post
{
    //!!!! use for derived
    public class EditablePostModel : BasicPostModelWithTagsAndUser
    {
        [UsePermissionsCheck]
        public bool CanEditPost { get; set; }
    }
}

Blog/Models/Post/FullDisplayPostModel.cs
using Blog.App.Models.Comment;
using System.Collections.Generic;
using Automapper.ModelsConverters.Attributes;

namespace Blog.App.Models.Post
{
    //use for derived
    public class FullDisplayPostModel : BasicPostModelWithTagsAndUser
    {
        [UseViewModelConverter]
        public IEnumerable<DisplayCommentModel> Comments { get; set; }
        [UsePermissionsCheck]
        public bool CanAddComment { get; set; }
    }
}

Blog/Models/Post/NotificationMessageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.App.Models.Post
{
    public class NotificationMessageModel
    {
        public string ClientId { get; set; }
        public int PositionId { get; set; }
        public string UserEmail { get; set; }
    }
}

Blog/Models/Post/ShortDisplayPostModel.cs
using Blog.App.Models.User;


namespace Blog.App.Models.Post
{
    //use for derived
    public class ShortDisplayPostModel : EditablePostModel
    {
        //public BasicUserModel User { get; set; }
    }
}

Blog/Controllers/PostController.cs
using Automapper.Contracts;
using Blog.App.Authorization;
using Blog.App.Contracts;
using Blog.App.Models.Device;
using Blog.App.Models.Post;
using Blog.App.SignalR;
using Blog.Data.Contracts;
using Blog.Data.Models;
using Blog.Lib.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Localization;
using Newtonsoft.Json;
using System;
using System.Net;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Blog.App.Controllers
{
    public class PostController : Controller
    {

        private readonly IBlogLogic _blogLogic;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IStringLocalizer<PostController> _stringLocalizer;
        private readonly IHubContext<EditPostHub> _hubContext;

        public PostController(IUnitOfWork unitOfWork, IBlogLogic blogLogic, IStringLocalizer<PostController> stringLocalizer, IHubContext<EditPostHub> hubContext)
        {
            _blogLogic = blogLogic;
            _unitOfWork = unitOfWork;
            _stringLocalizer = stringLocalizer;
            _hubContext = hubContext;
        }

        private void SetRedirectUrl()
        {
            TempData["redirectUrl"] = Request.Headers["Referer"].ToString();
        }

        private string GetRedirectUrl()
        {
            object url = null;
            var doesntExist = TempData == null || !TempData.TryGetValue("redirectUrl", out url);
            if (doesntExist || url == null)
            {
                return "/";
            }
            return url.ToString();
        }

        [HttpGet]
        [Authorize(Policy = "NotBanned")]
        public IActionResult Create(long blogId)
        {
            SetRedirectUrl();
            var displayModel = new EditPostModel();
            displayModel.BlogId = blogId;
            return View("EditPost", displayModel);
        }

        [HttpGet]
        [Authorize(Policy = "NotBanned")]
        public IActionResult Edit(long postid, [FromServices] IModelConverter<EditPostModel, Post> converter)
        {
            SetRedirectUrl();
            var post = _unitOfWork.PostRepository.GetById(postid);
            if (post == null)
            {
                return View("Error", _stringLocalizer["PostNotFound"].Value);
            }

            var displayModel = converter.Convert(post);
            return View("EditPost", displayModel);
        }


        [HttpPost]
        public IActionResult Delete(EditPostModel editPostModel)
        {
            var post = _unitOfWork.PostRepository.GetById(editPostModel.Id);
            if (post == null || _blogLogic.DeletePost(post, User.GetId()))
            {
                return Redirect(GetRedirectUrl());
            }

            return View("Error", _stringLocalizer["AccessDenied"].Value);
        }

        [HttpPost]
        public void Cancel()
        {
            Response.Redirect(GetRedirectUrl());
        }

        [HttpPost]
        [Authorize(Policy = "NotBanned")]
        public IActionResult Save([FromForm]EditPostModel editPostModel, [FromServices] IModelUpdating<Post, EditPostModel> converter)
        {
            if (!ModelState.IsValid)
            {
                return View("EditPost", editPostModel);
            }

            Post post;
            if (!_blogLogic.IsExisting(editPostModel.Id))
            {
                post = new Post();
                converter.Update(editPostModel, post);

                if (!_blogLogic.AddPost(post, User.GetId()))
                {
                    return View("Error", _stringLocalizer["AccessDenied"].Value);
                }
            }
            else
            {
                post = _unitOfWork.PostRepository.GetById(editPostModel.Id);
                converter.Update(editPostModel, post);
                if (!_blogLogic.UpdatePost(post, User.GetId()))
                {
                    return View("Error", _stringLocalizer["AccessDenied"].Value);
                }
            }

            return Redirect(GetRedirectUrl());
        }


        [HttpGet]
        public IActionResult Post(long id, [FromServices] IBlogAppUserRelatedModelConverter<FullDisplayPostModel, Post> converter)
        {
            SetRedirectUrl();
            var post = _unitOfWork.PostRepository.GetById(id);
            if (post == null)
            {
                return View("Error", _stringLocalizer["PostNotFound"].Value);
            }
            var displayModel = converter.ConvertUserRelated(post, User.GetId());
            return View("FullDisplayPost", displayModel);
        }

        [HttpGet]
        public void Back()
        {
            Response.Redirect(GetRedirectUrl());
        }

        [HttpPost]
        public async Task<IActionResult> SendNotification(int positionId, string connectionId)
        {
            var returnCode = HttpStatusCode.InternalServerError;

            var notification = new NotificationMessageModel
            {
                UserEmail = User.Identity.Name,
                ClientId = connectionId,
                PositionId = positionId
            };

            var notificationContent = JsonConvert.SerializeObject(notification);
            notificationContent = notificationContent.Replace("\"", "\\\"");
            var jsonNotification = "{ \"data\" : { \"message\":\"" + notificationContent + "\"}}";

            try
            {
                var outcome = await Notifications.Instance.Hub.SendFcmNativeNotificationAsync(jsonNotification, User.Identity.Name);

                if (outcome != null)
                {
                    if (!((outcome.State == Microsoft.Azure.NotificationHubs.NotificationOutcomeState.Abandoned) ||
                        (outcome.State == Microsoft.Azure.NotificationHubs.NotificationOutcomeState.Unknown)))
                    {
                        returnCode = HttpStatusCode.OK;
                    }
                }
            }
            catch(Exception ex)
            {
                Response.StatusCode = 2;
                Response.Headers.Add("exception", ex.ToString());
                return null;
            }

            return StatusCode((int)returnCode);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Photo([FromBody]Image image)
        {
            var user = _hubContext.Clients.Client(image.CLientId);

            await user.SendAsync("Send", image);

            return StatusCode((int)HttpStatusCode.OK);
        }

    }
}

Blog/Views/Post/EditPost.cshtml
@model EditPostModel
@inject IViewLocalizer localizer
@{
    ViewData["Title"] = "EditPost";
}


<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src='@Url.Content("~/js/jquery.signalR-2.4.0.min.js")'></script>
<script type="text/javascript" src='@Url.Content("~/js/signalr.min.js")'></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>  

<script  type="text/javascript">
    
    var tags = [];
    @if (Model.Tags != null)
    {
        @foreach (var tag in Model.Tags)
        {
            var value = tag.TagText;
            var id = tag.Id;
            @: tags.push(["@value", "@id"]);
        }
    }
</script>
<script src='@Url.Content("~/js/EditPost.js")'></script>

<link href='@Url.Content("~/css/Tag.css")' rel="stylesheet" type="text/css" />
<link href='@Url.Content("~/css/EditComponents.css")' rel="stylesheet" type="text/css" />
<link href='@Url.Content("~/css/Shared.css")' rel="stylesheet" type="text/css" />

<div id="PostTags" style="height:auto">
    @if (Model.Tags != null)
    {
        @foreach (var tag in Model.Tags)
        {
            var id = "Tag" + tag.TagText;
            var buttonId = "delete" + tag.TagText;
            <div id="@id" style="display:inline">
                <div class="tag-card nohover">
                    @tag.TagText
                </div>
                <button id="@buttonId" class="delete-tag-button" onclick="deleteTag(this.id)">X</button>
            </div>
        }
    }
    </div>

<div class="addImageDiv">
    <label>Load image from remote device</label>
    <button onclick="requestImage()" disabled id="loadImageRemoteButton">Load</button>
</div>

<div class="addImageDiv">
    <label>Load image from your computer</label>
    <input type="file" id="fileInput" />
</div>
<form action="" method="post" id="postform">
    <div>
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.BlogId)
        @Html.ValidationSummary()
        <div id="FormTags" style="height:auto" class="form-group">           
        </div>
        <div>
            <label class="edit-label" for="Tags">@localizer["Tags"]</label>
            <input type="text" id="Tags" class="edit-component" style="font-size:large;" />
        </div>
        <div>
            <label class="edit-label" for="Title">@localizer["Title"]</label>
            <textarea asp-for="PostTitle" class="edit-component" style="font-size:large;height:100px;">@Model.PostTitle</textarea>
        </div>
        <div>
            <input type="hidden" name="PostText" value="" id="postTextInput"/>
            
            <div contenteditable="true" class="edit-component" id="postTextDiv">@Html.Raw(Model.PostText)</div>

            <span class="edit-component" asp-validation-for="PostText"></span>
        </div>
        
    </div>
    <div>
        <button class="btn btn-success" type="submit" style="margin:30px" formaction="save">@localizer["Save"]</button>
        <button class="btn btn-danger" type="submit" style="margin:30px" formaction="delete">@localizer["Delete"]</button>
        <button class="btn btn-default" type="submit" style="margin:30px" formaction="cancel">@localizer["Cancel"]</button>
    </div>
</form>

Blog/Views/Post/FullDisplayPost.cshtml
@model Blog.App.Models.Post.FullDisplayPostModel
@inject IViewLocalizer localizer
@{
    ViewData["Title"] = "FullDisplayPost";
}
@*12*@
<script src="//code.jquery.com/jquery-1.6.4.js"></script>
<script type ="text/javascript" src='@Url.Content("~/js/signalr.min.js")'></script>
<script src='@Url.Content("~/js/jquery.signalR-2.4.0.min.js")'></script>
<script type="text/javascript" src='@Url.Content("~/js/FullDisplayPost.js")'></script>
<script type="text/javascript">
    $(document).ready(function () {
        setupHubConnection(@Model.Id);
    });
</script>
<link href='@Url.Content("~/css/Shared.css")' rel="stylesheet" type="text/css" />
<link href='@Url.Content("~/css/EditComponents.css")' rel="stylesheet" type="text/css" />
<link href='@Url.Content("~/css/InfoContainer.css")' rel="stylesheet" type="text/css" />

<div>
    <a asp-controller="Post" asp-action="Back" style="float:left;">@localizer["Back"]</a>
    <div class="title post-title">
        <p>@Model.PostTitle</p>
    </div>
    <div class="sidebar user-full-display-post">
        <partial name="UserCard" for="User" />
        <p class="date">@Model.DatePublished</p>
    </div>
    
    <div class="content" style="height:auto; width:auto;">
        <p class="text" style="height:auto;">@Html.Raw(Model.PostText)</p>
        <partial name="_TagCollection" for="@Model.Tags" />
    </div>
    <div>
        @if (Model.CanAddComment)
        {
            <textarea id="comment" maxlength="1500" class="comment">@localizer["AddComment"]</textarea>
            <button class="btn btn-success" id="AddCommentButton" onclick="AddComment(@Model.Id)">@localizer["Add"]</button>
        }
    </div>
    <h2>Comments</h2>
    <div id="Comments">
        @foreach (var comment in Model.Comments)
        {
            <partial name="/Views/Comment/_Comment.cshtml" for="@comment" />
        }
    </div>
</div>

Blog/Views/Post/_ShortDisplayPost.cshtml
@model EditablePostModel
@inject IViewLocalizer localizer
@addTagHelper Blog.App.TagHelpers.TrimTextTagHelper, Blog.App
@{
    ViewData["Title"] = "_ShortDisplayPost";
}


<link href='@Url.Content("~/css/Shared.css")' rel="stylesheet" type="text/css" />


<div class="card">
    <div class="sidebar">
        @if (ViewBag.HideUserCard == null || !ViewBag.HideUserCard)
        {
            <partial name="UserCard" for="@Model.User" />
        }
        <p class="sidebar-info">@Model.DatePublished</p>
        @if (Model.CanEditPost)
        {
            <p class="sidebar-info"><a class="btn btn-default" asp-controller="Post" asp-action="Edit" asp-route-postid="@Model.Id">@localizer["Edit"]</a></p>
        }
    </div>
        <div class="title">
            <a max-length="100" class="title" asp-controller="Post" asp-action="Post" asp-route-id="@Model.Id">@Model.PostTitle</a>
        </div>
        <div class="content">
            <p max-length="400" id="shortPostText" shortPostText class="text">@Model.PostText</p>
            <partial name="_TagCollection" for="@Model.Tags" />
        </div>

</div>