Blog/Controllers/SearchPostsController.cs
using Blog.Lib.Contracts;
using Blog.Data.Contracts;
using Microsoft.AspNetCore.Mvc;
using Blog.App.Models.Search;
using Blog.App.Contracts;
using Microsoft.AspNetCore.Authorization;
using Blog.App.Authorization;

namespace Blog.App.Controllers
{
    [Authorize]
    public class SearchPostsController : Controller
    {

        [HttpGet]
        public IActionResult Search()
        {
            var model = new AllPostsSearchModel();
            model.CurrentUserId = User.GetId();
            return View("SearchPosts", model);
        }

        [HttpGet]
        public IActionResult Tags([FromQuery(Name = "tags")]long[] tags, [FromServices] ITagPostsSearcher searcher, int? page = 1)
        {
            page = page == null || page < 0 ? 1 : page;
            var model = searcher.Search(tags, User.GetId(), (int)page);
            return View("TagSearchResultPage", model);

        }

        [HttpPost]
        public IActionResult Search(AllPostsSearchResultModel model)
        {
            return RedirectToAction("All", model);
        }

        [HttpGet]
        public IActionResult All
        (
            BasicSearchModel model,
            [FromServices] IAllPostsSearcher searcher,
            int? page = 1
        )
        {
            page = page == null || page <= 0 ? 1 : page;
            var resultModel = searcher.Search(model, User.GetId(), (int)page);
            return View("SearchResultPage", resultModel);
        }

        [HttpGet]
        public void Mine()
        {
            Response.Redirect(Url.Action("All", "SearchPosts", new { currentUserOnly = true }));
        }

    }
}

Blog/ViewComponents/BlogsSelectorViewComponent.cs
using Automapper.Contracts;
using Blog.App.Models.Blog;
using Blog.Data.Contracts;
using Blog.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.App.ViewComponents
{
    public class BlogsSelectorViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IModelUpdating<BasicBlogModel, Blogg> _blogModelConverter;
        private readonly IStringLocalizer<BlogsSelectorViewComponent> _stringLocalizer;
        public BlogsSelectorViewComponent(IUnitOfWork unitOfWork, IModelUpdating<BasicBlogModel, Blogg> blogModelConverter, IStringLocalizer<BlogsSelectorViewComponent> stringLocalizer)
        {
            _unitOfWork = unitOfWork;
            _blogModelConverter = blogModelConverter;
            _stringLocalizer = stringLocalizer;
        }

        public async Task<IViewComponentResult> InvokeAsync(long currentUserId)
        {
            var blogs = await _unitOfWork
                .BlogRepository
                .GetBlogsByOwner(currentUserId);

            var result = new List<BasicBlogModel>();
            result.Add(new BasicBlogModel { Id = 0, BlogTitle = _stringLocalizer["None"].Value });
            result.AddRange(blogs.Select(x => _blogModelConverter.Convert(x)));

            return View("_BlogsSelector.cshtml", result);
        }
    }
}

Blog/Views/SearchPosts/SearchPosts.cshtml
@model AllPostsSearchModel
@inject IViewLocalizer localizer
@{
    ViewData["Title"] = "SearchPosts";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script language="javascript" type="text/javascript">

    $(document).ready(function () {
        OnDocReady();
    });

    function DisableUsername() {
        $("#UsernameInput").val('');
        $("#UsernameInput").attr('disabled', 'disabled');
    };

    function EnableUsername() {
        $("#UsernameInput").removeAttr('disabled');
    };

    function DisableCurrentUserOnly() {
        $("#OnlyCurrentUserCheckBox").prop('checked', false);
        $("#OnlyCurrentUserCheckBox").attr('disabled', 'disabled');
    };

    function EnableCurrentUserOnly() {
        $("#OnlyCurrentUserCheckBox").removeAttr('disabled');
    };

    function DisableBlogSelector() {
        $("#BlogSelector").val(0);
        $("#BlogSelector").attr('disabled', 'disabled');
    };

    function EnableBlogSelector() {
        $("#BlogSelector").removeAttr('disabled');
    };

    function OnBlogChanged() {
        var newvalue = document.getElementById("BlogSelector").value;
        if (newvalue != 0) {
            DisableCurrentUserOnly();
            DisableUsername();
        }
        else {
            EnableCurrentUserOnly();
            EnableUsername();
        }
    };

    function OnCurrentUserOnlyChanged() {
        var newvalue = $("#OnlyCurrentUserCheckBox").is(":checked");
        if (newvalue) {
            DisableUsername();
            DisableBlogSelector();
        } else {
            EnableUsername();
            EnableBlogSelector();
        }
    };

    function OnDocReady() {
        var newvalue = $("#OnlyCurrentUserCheckBox").is(":checked");
        var blognewvalue = document.getElementById("BlogSelector").value;
        if (blognewvalue != 0 || newvalue) {
            DisableUsername();
        }
        if (newvalue) {
            DisableBlogSelector();
        }
        if (blognewvalue != 0) {
            DisableCurrentUserOnly();
        }
    };
</script>

<link href='@Url.Content("~/css/Shared.css")' rel="stylesheet" type="text/css" />
<link href='@Url.Content("~/css/SearchPostsFields.css")' rel="stylesheet" type="text/css" />

<form asp-controller="SearchPosts" asp-action="Search" id="SearchForm">
    <div class="search-div">
        <label class="search-label">@localizer["OnlyMy"]</label>
        <input type="checkbox" asp-for="CurrentUserOnly" id="OnlyCurrentUserCheckBox" onchange="OnCurrentUserOnlyChanged()" />
    </div>
    <div class="search-div" >
        <label class="search-label">@localizer["Username"]</label>
        <input asp-for="UserName" class="username" id="UsernameInput" />
    </div>
    <div class="search-div">
        <label class="search-label">@localizer["TagsOrWords"]</label>
        <textarea asp-for="TagsOrWords" class="tags-or-words" id="TagsOrWords"></textarea>
    </div>
    <div class="search-div">
        <label class="search-label">@localizer["MyBlogs"]</label>
        <select asp-for="BlogId" id="BlogSelector" onchange="OnBlogChanged()">
            @await Component.InvokeAsync("BlogsSelector", new { currentUserId = Model.CurrentUserId})
        </select>
    </div>
    <div>
        <button class="btn btn-success" style="margin:20px;" type="submit">@localizer["Search"]</button>
    </div>
</form>

Blog/Views/SearchPosts/SearchResultPage.cshtml
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@using System.Web;

@model AllPostsSearchResultModel
@{
    ViewData["Title"] = "SearchResultPage";
}

<div>
    <div>
        @foreach (var post in Model.PostCollection)
        {
            <partial name="~/Views/Post/_ShortDisplayPost.cshtml" for="@post" />
        }
    </div>
    @Html.PagedListPager((IPagedList)Model.PostCollection, page => Url.Action("All", "SearchPosts", new { page = page, username = Model.UserName, tagsorwords = HttpUtility.UrlEncode(Model.TagsOrWords), currentUserOnly = Model.CurrentUserOnly, blogid = Model.BlogId }))
</div>

Blog/Views/SearchPosts/TagSearchResultPage.cshtml
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@inject IViewLocalizer localizer

@model TagsPostsSearchResultModel
@{
    ViewData["Title"] = "SearchResultPage";
    var searchTagsIds = Model.Tags.Select(t => t.Id).ToArray();
    ViewData["SearchTags"] = searchTagsIds;
    var independentTagModels = Model.Tags
        .Select(x => new TagModel { Id = x.Id, TagText = x.TagText})
        .ToList();
    independentTagModels.ForEach(x => x.IncludeSearchPosts = false);

}

<div>
    <a class="btn btn-default" href="@Url.Action("All", "SearchPosts")" style="margin:20px;">@localizer["Clear"]</a>
    <div style="margin:20px">
        <partial name="~/Views/Shared/_TagCollection.cshtml" for="@independentTagModels"/>
    </div>
    <div>
        @foreach (var post in Model.PostCollection)
        {
            <partial name="~/Views/Post/_ShortDisplayPost.cshtml" for="@post" />
        }
    </div>
@Html.PagedListPager((IPagedList)Model.PostCollection, page => Url.Action("Tags", "SearchPosts", new { tags =  searchTagsIds, page = page }))
</div>

Blog/Views/SearchPosts/_BlogsSelector.cshtml
@model List<BasicBlogModel>
@{
    ViewData["Title"] = "_BlogsSelector";
}



@foreach (var blog in Model)
{
    <option value="@blog.Id">@blog.BlogTitle</option>
}