Blog/Models/Blog/BasicBlogModel.cs
namespace Blog.App.Models.Blog
{
    //use basic
    public class BasicBlogModel
    {
        public long Id { get; set; }
        public string BlogTitle { get; set; }
    }
}

Blog/Models/Blog/BlogSelectorDisplayModel.cs
using System.Collections.Generic;


namespace Blog.App.Models.Blog
{
    //selected is not needed and just change to list of basic
    //public class BlogSelectorDisplayModel
    //{
    //    public List<BasicBlogModel> Options { get; set; }
    //    public long? Selected { get; set; }
    //}
}

Blog/Models/Blog/EditBlogModel.cs
using Blog.App.Contracts;
using Blog.App.ModelsConverters.Attributes;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;


namespace Blog.App.Models.Blog
{
    //use basic converter
    public class EditBlogModel
    {
        public long Id { get; set; }
        [Required]
        public string BlogTitle { get; set; }

        [UseFormFileConverter]
        public IFormFile PhotoPath { get; set; }
    }
}

Blog/Models/Blog/FullDisplayBlogModel.cs
using Blog.App.Models.Post;
using Blog.App.Models.User;
using Automapper.ModelsConverters.Attributes;

namespace Blog.App.Models.Blog
{
    public class FullDisplayBlogModel : BasicBlogModel
    {
        [UseViewModelConverter]
        public BasicUserModel Owner { get; set; }
        public EditablePostModel LatestPost { get; set; }
        public string PhotoPath { get; set; }
    }
}

Blog/Models/Blog/ShortDisplayBlogModel.cs
using Automapper.ModelsConverters.Attributes;


namespace Blog.App.Models.Blog
{
    //use for derived
    public class ShortDisplayBlogModel : BasicBlogModel
    {
        [UsePermissionsCheck]
        public bool CanEditBlog { get; set; }
    }
}

Blog/Controllers/BlogController.cs
using Blog.Data.Models;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;
using Blog.App.Contracts;
using Blog.App.Models.Blog;
using Blog.Data.Contracts;
using Blog.Lib.Contracts;
using Blog.App.Models.Post;
using Blog.App.Authorization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Options;
using Blog.App.Configuration;
using Microsoft.Extensions.Localization;
using Automapper.Contracts;

namespace Blog.App.Controllers
{
    public class BlogController : Controller
    {

        private readonly IBlogLogic _blogLogic;
        private readonly IUnitOfWork _unitOfWork;
        private int _pageSize;
        private readonly IStringLocalizer<BlogController> _stringLocalizer;

        public BlogController(IUnitOfWork unitOfWork, IBlogLogic blogLogic, IOptions<CustomSettings> options, IStringLocalizer<BlogController> stringLocalizer)
        {
            _blogLogic = blogLogic;
            _unitOfWork = unitOfWork;
            _pageSize = options.Value.PageSize;
            _stringLocalizer = stringLocalizer;

        }

        [HttpGet]
        [Authorize(Policy = "NotBanned")]
        public IActionResult Create()
        {
            var createBlogModel = new EditBlogModel();
            return View("EditBlog", createBlogModel);
        }

        [HttpGet]
        [Authorize(Policy = "NotBanned")]
        public IActionResult Edit(long blogId, [FromServices] IModelConverter<EditBlogModel, Blogg> converter)
        {
            var blog = _unitOfWork.BlogRepository.GetById(blogId);
            if (blog == null)
            {
                return View("Error", _stringLocalizer["BlogDoesntExist"].Value);
            }
            var editBlogModel = converter.Convert(blog);
            return View("EditBlog", editBlogModel);
        }

        [HttpPost]
        [Authorize(Policy = "NotBanned")]
        public IActionResult Edit(EditBlogModel editBlogModel, [FromServices] IModelUpdating<Blogg, EditBlogModel> converter)
        {
            if (!ModelState.IsValid)
            {
                return View("EditBlog", editBlogModel);
            }

            Blogg blog;
            blog = _unitOfWork.BlogRepository.GetById(editBlogModel.Id);
            if (blog == null)
            {
                blog = new Blogg();
            }

            converter.Update(editBlogModel, blog);

            if (!_blogLogic.AddOrUpdateBlog(blog, User.GetId()))
            {
                return View("Error", _stringLocalizer["AccessDenied"].Value);
            }

            return RedirectToAction("Index", "User", new { id = User.GetId() });
        }

        [HttpPost]
        public IActionResult Delete(EditBlogModel editBlogModel)
        {
            var blog = _unitOfWork.BlogRepository.GetById(editBlogModel.Id);
            if (blog != null)
            {
                if (!_blogLogic.DeleteBlog(blog, User.GetId()))
                {
                    return View("Error", _stringLocalizer["AccessDenied"].Value);
                }
            }
            return RedirectToAction("Index", "User", new { id = User.GetId() });
        }

        [HttpPost]
        public void Cancel()
        {
            Response.Redirect(Url.Action("Index", "User", new { id = User.GetId() }));
        }

        [HttpGet]
        public IActionResult Blog(long id, [FromServices] IBlogAppUserRelatedModelConverter<FullDisplayBlogModel, Blogg> converter)
        {
            var blog = _unitOfWork.BlogRepository.GetById(id);
            if (blog == null)
            {
                return View("Error", _stringLocalizer["BlogDoesntExist"].Value);
            }

            var displayModel = converter.ConvertUserRelated(blog, User.GetId());
            return View("FullDisplayBlog", displayModel);
        }

        [HttpGet]
        public IActionResult Posts(long blogId, int? page, [FromServices] IBlogAppUserRelatedModelConverter<EditablePostModel, Post> converter)
        {
            var postCollection = GetBlogPostsPagedList(blogId, converter, page);
            ViewBag.Posts = postCollection;
            ViewBag.BlogId = blogId;
            return View("BlogPosts", postCollection);
        }

        private IPagedList<EditablePostModel> GetBlogPostsPagedList(long blogId, IBlogAppUserRelatedModelConverter<EditablePostModel, Post> converter, int? page = null)
        {
            page = page == null || page <= 0 ? 1 : page;
            var posts = _unitOfWork.PostRepository.GetPostsByBlogId(blogId);
            var postCollection = posts
                .ToPagedList((int)page, _pageSize)
                .Select(x => converter.ConvertUserRelated(x, User.GetId()));
            return postCollection;
        }
    }
}

Blog/ViewComponents/BlogPostsAmountViewComponent.cs
using Blog.Data.Contracts;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Blog.App.ViewComponents
{
    public class BlogPostsAmountViewComponent : ViewComponent
    {
        public IUnitOfWork _unitOfWork;
        public BlogPostsAmountViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync(long blogId)
        {
            var amount = _unitOfWork
                .BlogRepository
                .GetPostsAmount(blogId);

            return View("_Text.cshtml", amount);
        }
    }
}

Blog/Views/Blog/BlogPosts.cshtml
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@inject IViewLocalizer localizer
@{
    ViewData["Title"] = "PagedPostCollection";
    var posts = (IPagedList)ViewBag.Posts; 
}


<div>
    <div style="margin:10px 60px;">
        <a class="btn btn-default" asp-controller="Blog" asp-action="Blog" asp-route-id="@ViewBag.BlogId">@localizer["Back"]</a>
    </div>
</div>
<div >
    @foreach(var post in ViewBag.Posts)
    {
        <partial name="~/Views/Post/_ShortDisplayPost.cshtml" for="@post"/>
    }
    @Html.PagedListPager((IPagedList)ViewBag.Posts, page => Url.Action("Posts", "Blog", new { blogid = ViewBag.BlogId, page = page }))
</div>

Blog/Views/Blog/EditBlog.cshtml
@model EditBlogModel
@inject IViewLocalizer localizer
@{
    ViewData["Title"] = "EditBlog";
}

<link href='@Url.Content("~/css/EditComponents.css")' rel="stylesheet" type="text/css" />
 
<form action="" method="post" enctype="multipart/form-data">
    <div>
        @Html.HiddenFor(m => m.Id)
        <div>
            <label class="edit-label" for="Title">@localizer["Title"]</label>
            <textarea asp-for="BlogTitle" class="edit-component" style="font-size:large;height:100px;">@Model.BlogTitle</textarea>
            <span class="edit-component" asp-validation-for="BlogTitle"></span>
        </div>
        <div>
            <label class="edit-label">@localizer["Background"]</label>
            <input type="file" accept="image/*" asp-for="PhotoPath" class="edit-component" />
        </div>
    </div>
    <div>
        <button class="btn btn-success" type="submit" style="margin:30px" formaction="edit">@localizer["Save"]</button>
        <button class="btn btn-danger" type="submit" style="margin:30px" formaction="delete">@localizer["Delete"]</button>
        <button class="btn btn-default" type="submit" style="margin:30px" formaction="cancel">@localizer["Cancel"]</button>
    </div>
</form>

Blog/Views/Blog/FullDisplayBlog.cshtml
@model FullDisplayBlogModel
@inject IViewLocalizer localizer
@{
    ViewData["Title"] = "FullDisplayBlog";
    ViewBag.HideUserCard = true;
}

<script src='@Url.Content("~/lib/Microsoft.jQuery.Unobtrusive.Ajax/jquery.unobtrusive-ajax.min.js")'></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>

<link href='@Url.Content("~/css/InfoContainer.css")' rel="stylesheet" type="text/css" />
<link href='@Url.Content("~/css/FullDisplayBlog.css")' rel="stylesheet" type="text/css" />

<div class="im-container">
    <div>
        <partial name="UserCard" for="@Model.Owner" />
    </div>
    <img src="@{@Model.PhotoPath}" default-src="defaultblog.png" height="350" width="1000" />
</div>

<div>
    <div class="info-label">
        <p>@Model.BlogTitle</p>
    </div>
    <div class="info-label">
        <p>@localizer["PostsAmount"]</p>
        @await Component.InvokeAsync("BlogPostsAmount", new { blogId = Model.Id })
    </div>
</div>

@if (Model.LatestPost != null)
{
    <div>
        <div class="info-label">
            <p>@localizer["LatestPost"]</p>
        </div>

        <partial name="~/Views/Post/_ShortDisplayPost.cshtml" for="@Model.LatestPost" />

        <div class="info-label">
            <a asp-controller="Blog" asp-action="Posts" asp-route-blogid="@Model.Id">@localizer["More"]</a>
        </div>
    </div>
}

Blog/Views/Blog/_Text.cshtml
@model object
@{
    ViewData["Title"] = "_Text";
}

<p>@Model.ToString()</p>